services:
  nvidia-tensorflow:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: vscode
        USERGROUP: vscode
    container_name: nvidia-tensorflow
    tty: true
    working_dir: /workspace
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ..:/workspace
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
